FROM golang:1.25-alpine AS builder

# Устанавливаем рабочую директорию внутри контейнера
WORKDIR /demon

#  Копируем файлы проекта в контейнер
COPY . .

# Сборка второго приложения (runDemon)
RUN go build -o runDemon ./cmd/runDemon/Dmain.go

CMD ["./runDemon"]